#!/bin/bash

set -e # kill script if there is an error

EXEC="./evaluation_predictive.native"
GRAPHS=graphs-predictive
SRC=$1/gpx #take working dir as first argument
GEOLIFE=geolife-trajectories-1.3


echo Convert geolife .plt files to .gpx
mkdir -p $SRC
OCAMLRUNPARAM=b $EXEC geolife2gpx $GEOLIFE/Data $SRC-tree
cp $SRC-tree/*/Trajectory/*.gpx $SRC

echo filter
$EXEC filter $SRC &> $SRC-filtered.dump 

echo sample every 30 minutes
(/usr/bin/time -v $EXEC sample $SRC-filtered 1 30 5) &> $SRC-filtered-sampled-1-30-5.dump
echo sample every 60 minutes
(/usr/bin/time -v $EXEC sample $SRC-filtered 1 60 5) &> $SRC-filtered-sampled-1-60-5.dump

ARGS=(\
"0.6  0.   10. false"\ 
"0.6  0.   10. true "\ 
"0.75 0.   30. false"\ 
"0.75 0.   30. true "\ 
"0.6  1000. 0. false"\ 
"0.6  1000. 0. true "\ 
"0.7  3000. 0. false"\ 
"0.7  3000. 0. true ") 

echo sanitize sample 30m
LOG=$SRC-filtered-sampled-1-30-5-sanitized.dump
echo run 1-30-5 &> $LOG
for i in ${!ARGS[*]}
do
    echo ${ARGS[$i]} &>> $LOG
    (/usr/bin/time -v $EXEC run $SRC-filtered-sampled-1-30-5 ${ARGS[$i]}) &>> $LOG
done

echo sanitize sample 60m
LOG=$SRC-filtered-sampled-1-60-5-sanitized.dump
echo run 1-60-5 &> $LOG
for i in ${!ARGS[*]}
do
    echo ${ARGS[$i]} &>> $LOG
    (/usr/bin/time -v $EXEC run $SRC-filtered-sampled-1-60-5 ${ARGS[$i]}) &>> $LOG
done

echo generate graphs
for i in $(ls -d $SRC-*-sanitized); do $GRAPHS $i; done
